/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto1.Vistas;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import proyecto1.Modelos.Cliente;
import proyecto1.Modelos.Cuenta;

/**
 *
 * @author ppabl
 */
public class CrearCuenta extends javax.swing.JFrame {
    private List<Cliente> listaClientes;
    private List<Cuenta> listaCuentas;

    /**
     * Creates new form CrearCuenta
     */
    public CrearCuenta(List<Cliente> clientes, List<Cuenta> cuentas) {
        super("Crear Cuenta");
        initComponents();
        
        // Inicializar listas
        this.listaClientes = (clientes != null) ? clientes : new ArrayList<>();
        this.listaCuentas = (cuentas != null) ? cuentas : new ArrayList<>();
        
        cargarClientes();
    }
    
    private void cargarClientes() {
        comboClientes.removeAllItems(); 

        if (listaClientes.isEmpty()) {
            comboClientes.addItem("No hay clientes registrados");
            return;
        }
        for (Cliente cliente : listaClientes) {
            String item = "CUI: " + cliente.getCui() + " - " + cliente.getNombre() + " " + cliente.getApellido();
            comboClientes.addItem(item);
        }
    }

    private Cliente obtenerClientePorCUI(String cui) {
        for (Cliente cliente : listaClientes) {
            if (cliente.getCui().equals(cui)) {
                return cliente;
            }
        }
        return null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        comboClientes = new javax.swing.JComboBox<>();
        btnCrearCuenta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Cliente");

        comboClientes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnCrearCuenta.setText("jButton1");
        btnCrearCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearCuentaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCrearCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(177, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnCrearCuenta)
                .addContainerGap(157, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearCuentaActionPerformed
        String seleccion = (String) comboClientes.getSelectedItem();

        if (seleccion == null || seleccion.equals("No hay clientes registrados")) {
            JOptionPane.showMessageDialog(this, "Por favor, selecciona un cliente válido.");
            return;
        }

        try {
            String[] partes = seleccion.split(": ");
            if (partes.length < 2) {
                throw new Exception("Formato incorrecto en selección.");
            }

            String cuiSeleccionado = partes[1].split(" - ")[0]; // Extraer solo el CUI
            Cliente cliente = obtenerClientePorCUI(cuiSeleccionado);

            if (cliente == null) {
                JOptionPane.showMessageDialog(this, "Error: Cliente no encontrado.");
                return;
            }

            if (cliente.getCuentas().size() >= 4) {
                JOptionPane.showMessageDialog(this, "Este cliente ya tiene el límite de cuentas.");
                return;
            }

            // Generar un número de cuenta único
                String numeroCuenta = generarNumeroCuenta();
                // Agregar la cuenta al cliente
                cliente.agregarCuenta(nuevaCuenta);
                listaCuentas.add(nuevaCuenta);

            JOptionPane.showMessageDialog(this, "Cuenta creada exitosamente con saldo inicial de Q0.00.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al procesar la selección.");
        }
    }//GEN-LAST:event_btnCrearCuentaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearCuenta(new ArrayList<>(), new ArrayList<>()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrearCuenta;
    private javax.swing.JComboBox<String> comboClientes;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
